# Choose the Trainer and the Policy to train
trainer: "Trainer_PPO"

# Choose the Environment to load or "" for in Editor training
env_name: "./envs/CartPoleV1.exe"

# Choose trainer parameters passed to the trainer class
train_params: 

  # Number of epochs to run
  epochs: 1000
  # Steps per epoch
  steps_per_epoch: 500
  # max episode length -> termination
  max_episode_length: 500

  # discount factor
  gamma: 0.99
  # lambda factor for GAE
  lam: 0.97
  # starting seed for tensorflow and Env
  seed: 0
  
# Choose the policy parameters for training
policy_params:
  # learning rate Value Network
  lr_v:   0.001
  # leraning rate Policy Network
  lr_pi:  0.001
  
  train_pi_iters: 80    
  train_v_iters: 80
  hidden_sizes_pi: [64,32]
  hidden_sizes_v: [64,32,]
  clip_ratio: 0.2
  target_kl: 0.01

